services:
  db:
    container_name: {{cookiecutter.app_name}}_db
    image: postgres:${POSTGRES_VERSION:-7.4.1}-alpine${POSTGRES_ALPINE_VERSION:-3.21}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 3
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-dev_db}
      - POSTGRES_USER=${POSTGRES_USER:-dev_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASS:-dev_pass}
    networks:
      - app

volumes:
  postgres-data:
    name: {{cookiecutter.app_name}}_postgres_data
    driver: local

networks:
  app:
    name: {{cookiecutter.app_name}}_network
    driver: bridge
