services:
  cache:
    image: redis:${REDIS_VERSION:-7.4.1}-alpine${REDIS_ALPINE_VERSION:-3.20}
    container_name: {{cookiecutter.app_name}}_cache
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - app

volumes:
  redis-data:
    name: {{cookiecutter.app_name}}_redis_data
    driver: local

networks:
  app:
    name: {{cookiecutter.app_name}}_network
    driver: bridge
