dc := "docker compose"

file_app := "--file docker-compose.app.yaml"
file_db := "--file docker-compose.mongo.yaml"
file_cache := "--file docker-compose.redis.yaml"
file_broker := "--file docker-compose.kafka.yaml"

container_app := "app"
container_db := "db"

command := dc + " " + file_app + " " + file_db + " " + file_broker + " " + file_cache

default:
  just --list

install:
    deactivate || true
    rm -rf .venv
    python3.13 -m venv .venv
    . .venv/bin/activate
    poetry install

up args="":
  {{command}} up --build --remove-orphans {{args}}

down args="":
  {{command}} down {{args}}

test args="":
  {{command}} exec app python -m pytest {{args}}

ruff args="":
  ruff check ./src --fix

restart args="":
  {{command}} restart

app-restart args="":
  {{command}} restart {{container_app}} {{args}}

app-logs args="":
  {{command}} logs {{container_app}} {{args}}

app-migration-gen:
  {{command}} exec {{container_app}} alembic revision --autogenerate

app-migration-up:
  {{command}} exec {{container_app}} alembic upgrade head

sql-connect:
  {{command}} exec {{container_db}} psql -U dev_user kot-db

ci-build:
  {{command}} build

ci-test:
  {{command}} run --rm {{container_app}} sh -c "python -m pytest -s --sw -vvv"
