services:
  app:
    hostname: {{cookiecutter.app_name.lower()}}_app
    container_name: {{cookiecutter.app_name.lower()}}_app
    profiles:
      - api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=development
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: "python console.py run"
    healthcheck:
      test: ["CMD-SHELL", "python console.py check-health"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    env_file:
      - .env
    volumes:
      - ./src:/src
    networks:
      - app

networks:
  app:
    name: {{cookiecutter.app_name.lower()}}_app
    driver: bridge
