services:
  db:
    container_name: {{cookiecutter.app_name}}_db
    image: postgres:17.2-alpine3.21
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 3
    environment:
      - POSTGRES_DB=${SQL_DB:-dev_db}
      - POSTGRES_USER=${SQL_USER:-dev_user}
      - POSTGRES_PASSWORD=${SQL_PASS:-dev_pass}
    networks:
      - app

volumes:
  postgres-data:
    name: {{cookiecutter.app_name}}_postgres_data
    driver: local

networks:
  app:
    name: {{cookiecutter.app_name}}_network
    driver: bridge
