services:
  app:
    hostname: {{cookiecutter.app_name|lower|replace(' ', '_')}}_app
    container_name: {{cookiecutter.app_name|lower|replace(' ', '_')}}_app
    profiles:
      - api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=development
    ports:
      - ${APP_PORT}:8000
    command: "uvicorn --factory application.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:8000/check/health || exit 1"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    env_file:
      - .env
    volumes:
      - ./src:/src
    networks:
      - app

networks:
  app:
    name: {{cookiecutter.app_name|lower|replace(' ', '_')}}_app
    driver: bridge
