dc := "docker compose"

file_docker := "-f docker-compose.yml"

profile_api := "--profile api"

container_app := "abcde123_app"


default:
  just --list

install:
    rm -rf .venv
    python3.13 -m venv .venv
    . .venv/bin/activate
    poetry install
    pre-commit install
    pre-commit autoupdate --repo https://github.com/charliermarsh/ruff-pre-commit --repo https://github.com/pre-commit/pre-commit-hooks

up args="":
  {{dc}} {{file_docker}} {{profile_api}} up --build --remove-orphans {{args}}

down args="":
  {{dc}} {{file_docker}} {{profile_api}} down {{args}}

app-restart args="":
  docker restart {{container_app}} {{args}}

app-logs args="":
  docker logs {{container_app}} {{args}}
